### ISSUE TITLE
breakpoints

### ISSUE THREAD

**Issue by VivianeBusch-Wallace** [svenWacker/SAAViBooks#5]
I think we should adjust our breakpoints a little bit. The iPhone X for example has a width of 375px, older iPhones a littler bigger even.
So I suggest this ratio:
320px — 480px: Mobile devices
481px — 768px: iPads, Tablets
769px — 1024px: Small screens, laptops
1025px — 1200px: Desktops, large screens
1201px and more —  Extra large screens, TV

source: https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/

And instead of starting with width 320px I suggest we start with width 0px because we don't have a special layout for smaller than 320px.

**Comment by albaranlex** [comment]
I'll incorporate these breakpoints to my components.
